---
# chocomilk vars

# Package Changelog
changelog: "https://release-monitoring.org/api/v2/versions/?project_id=21215"
changelog_format: json

# Regex for Version
version: "{{ register_changelog.json['stable_versions'][0] }}"

# Download URL
url: "https://download.microsoft.com/download/6c1eeb25-cf8b-41d9-8d0d-cc1dbc032140/officedeploymenttool_{{ version.split('.')[-2:] | join('-') }}.exe"

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"

# readme to description
readme:
  start: 6
  end: 46

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.microsoft-office-deployment.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: "https://chat.open-circle.ch"
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: "notification-chocolatey"
