name: Keep workflows alive

# Runs once every week, triggers GitHub API if time_elapsed days
# have passed since last commit to keep actions active.
on:
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "chocomilk.yml"
          time_elapsed: 40
